owner: stealthtalent
repo: stealth-status

sites:
  - name: Website
    url: https://stealthtalent.work
  - name: API
    url: https://stealthtalent.work/health

status-website:
  publish: true
  cname: status.stealthtalent.work
  name: Stealth Talent Status
  logoUrl: https://raw.githubusercontent.com/stealthtalent/stealth-status/master/assets/stealth-logo.svg
  introTitle: "All systems operational"
  introMessage: Real-time monitoring for Stealth Talent services.
  theme: light
  themeUrl: https://raw.githubusercontent.com/stealthtalent/stealth-status/master/assets/stealth-theme.css
  navbar:
    - title: Status
      href: /
    - title: Stealth Talent
      href: https://stealthtalent.work
  css:
    - https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap
  customHeadHtml: >-
    <style>
      body, html {
        font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif !important;
      }
      .logo img {
        height: 28px !important;
      }
      h1 {
        font-weight: 600 !important;
      }
      footer {
        color: #8B8B8B !important;
      }
      footer a {
        color: #8B8B8B !important;
        text-decoration: underline !important;
      }
      nav a {
        color: #1A1A1A !important;
      }
      nav a:hover, nav a[aria-current] {
        color: #169A93 !important;
      }
    </style>
