owner: stealthtalent
repo: stealth-status

sites:
  - name: Website
    url: https://stealthtalent.work
  - name: API
    url: https://stealthtalent.work/health

status-website:
  publish: true
  cname: status.stealthtalent.work
  name: Stealth Talent Status
  introTitle: "**Stealth Talent** is up"
  introMessage: This page shows real-time monitoring for Stealth Talent services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
